# Site settings
title: sia karamalegos
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  my misadventures while learning to code.  entertain yourself or maybe
  learn something that will help you out on your own learning adventure.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://siakaramalegos.github.io/" # the base hostname & protocol for your site
twitter_username: thegreengreek
github_username:  siakaramalegos

# Build settings
markdown: kramdown

# How many posts to show before breaking to next page
# See http://jekyllrb.com/docs/pagination/ to build out fully.
# paginate: 5
